apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver-deploy
  name: resultserver-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resultserver-deploy
  template:
    metadata:
      labels:
        app: resultserver-deploy
    spec:
      containers:
      - image: raifehizlan/resultserver #I deleted the image from deckerhub
        name: resultserver
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: server-config
        - secretRef:
            name: mysql-secret
        # env:
        # - name: MYSQL_PASSWORD
        #   value: Clarusway_1
        # - name: MYSQL_USER
        #   value: clarus
        # - name: MYSQL_DATABASE
        #   value: phonebook
        # - name: MYSQL_DATABASE_HOST
        #   value: mysql
        resources: {}
